# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-04 04:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_auto_20170103_1838'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='kirrurl',
            managers=[
            ],
        ),
    ]
